using System.Text;

namespace Scout2.Report {
   public class Definitions {
      public static string AsString() {
         var sb = new StringBuilder();
         sb.Append("   <table border=\"1\">");
         sb.Append("      <caption>Definitions, (from California code when applicable)</caption>");
         sb.Append("      <tr>");
         sb.Append("         <th>Term</th>");
         sb.Append("         <th></th>");
         sb.Append("         <th>Definition</th>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Assembly Rule 56</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("            All standing committees meet at the hour and place provided by the Speaker, unless permission to change is granted by the Speaker.");
         sb.Append("            When an unscheduled meeting of a standing committee is ordered, it must convene in a readily accessible place for the public and the public should be informed of the hearing being called.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Assembly Rule 63</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("            All scheduled committee hearings, together with the list of bills to be heard, shall be published in the Daily File.");
         sb.Append("            The Daily File shall show");
         sb.Append("            <ul>");
         sb.Append("               <li>1. Special Orders of the Day</li>");
         sb.Append("               <li>2. Second Reading, Assembly Bills</li>");
         sb.Append("               <li>3. Second Reading, Senate Bills</li>");
         sb.Append("               <li>4. Unfinished Business</li>");
         sb.Append("               <li>5. Third Reading, Assembly Bills</li>");
         sb.Append("               <li>6. Third Reading, Senate Bills</li>");
         sb.Append("            </ul>");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Assembly Rule 69</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("            Floor amendments are not in order unless a copy of the proposed amendments has been placed upon the desks of the Members.");
         sb.Append("            There are quite a few additional details.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Assembly Rule 77</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("            Covers concurrence in any Senate Amendment to an Assembly bill.Asm has already passed the bill, Sen passed with some amendments,");
         sb.Append("            and now Asm is deciding whether to agree with those amendments.Before voting, the floor analyst must have placed an analysis");
         sb.Append("            on the desks of the members.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Assembly Rule 96</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("            A bill can be withdrawn from a committee only during the regular order of business and by a majority of the members present and voting.");
         sb.Append("            There are some other, less common, circumstances.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>BAA</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("            Bill Analysis Available (legislative analyst has written analysis of the bill). See NBA.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Chaptered</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>After being signed by the governor, a bill is filed with the Secretary of State and assigned a chapter number for reference and inclusion in the codes, of which there are 29 (Civil Code, Vehicle Code, etc.).</td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Consent Calendar</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>A group of noncontroversial bills passed by a committee to another committee or the full Assembly or Senate. Bills may be placed upon the Consent Calendar if they are reported to the Floor with that recommendation and (1) have received no \"no\" votes in committee and (2) have had no opposition expressed by any person present at the hearing.</td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Enrolled</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>Once a bill has passed the legislature, it goes to the governor for signature.The \"enrollment\" process includes the notation of the exact date and time each bill is sent to the Governor to sign or veto, or he may allow it to become law without signing.</td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Expect</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>(see expectations) Expect = Close to 100%. I'd bet money on it.</td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Expectations</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>Probably = over 50% confidence, Likely = over 75% confidence, Expect = Close to 100%. I'd bet money on it.</td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Held In Committee</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("           When a bill fails to get sufficient votes to pass out of committee, it is held in committeen a bill is heard in committee.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Held Under Submission</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("           An action taken by a committee when a bill is heard in committee and there is an indication that the author and the");
         sb.Append("           committee members want to work on or discuss the bill further, but there is no motion for the bill to progress out of committee. This does not preclude the bill");
         sb.Append("           from being set for another hearing.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Inactive File</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("           The portion of the Daily File containing legislation that is ready for floor consideration, but, for a variety of reasons, is dormant.");
         sb.Append("           An author may move a bill to the inactive file if he or she wishes to take it up at a later date.");
         sb.Append("           Once a bill is on the inactive file, one day's public notice is needed to place it back on the agenda.");
         sb.Append("        </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Joint Rule 56</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("           Bills introduced in the first year of the regular session and passed by the house of origin on or before the January 31st constitutional");
         sb.Append("           deadline are \"carryover bills.\" Immediately after January 31, bills introduced in the fi rst year of the regular session that do not become");
         sb.Append("            \"carryover bills\" shall be returned to the Chief Clerk of the Assembly or Secretary of the Senate, respectively.");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Likely</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>(see expectations) Likely = over 75% confidence</td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>NBA</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("           No Bill Analysis (legislative analyst has not written analysis of the bill).  See BAA.");
         sb.Append("        </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Probably</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>(see expectations) Probably = over 50% confidence</td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Psychiatric emergency medical condition</td>");
         sb.Append("         <td>1317.1(k)(1)</td>");
         sb.Append("         <td>");
         sb.Append("            a mental disorder that manifests itself by acute symptoms of sufficient severity that it renders the patient as being either of the following:");
         sb.Append("            <ul>");
         sb.Append("               <li>(A) An immediate danger to himself or herself or to others.</li>");
         sb.Append("               <li>(B) Immediately unable to provide for, or utilize, food, shelter, or clothing, due to the mental disorder.</li>");
         sb.Append("            </ul>");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Reconsiderations</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("           A motion that, if carried, allows a measure that failed or passed to be heard again in committee or on the Floor.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Senate Rule 28.8</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("            Any bill referred to the Committee on Appropriations...that does not appropriate money may not be set for hearing");
         sb.Append("            and shall...be reported to the Senate...placed on second reading.");
         sb.Append("            There are some specific conditions.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Sine Die</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("            without any future date being designated (as for resumption). Latin: without a day");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Suspense File</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("            A bill or set of bills, with a fiscal impact, set aside in Appropriations Committee by a majority of Members present and voting. These bills may be heard at a later hearing.");
         sb.Append("            <br />The suspense file is a holding placing for bills with significant fiscal impacts.Bills are generally held on the suspense file before each fiscal deadline so that each House can evaluate the total impacts to the state. Bills which are moved out of suspense then go to the floor while bills held in suspense die.");
         sb.Append("            <br />(Joe) I believe it is true that a fiscal impact bill which is placed in the suspense file does not have to arrive on the floor at the");
         sb.Append("            required date.Once the budget is approved, then the bill can be reactivated, passed by the appropriations committee, and sent to the floor.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("      <tr>");
         sb.Append("         <td>Two year bill</td>");
         sb.Append("         <td></td>");
         sb.Append("         <td>");
         sb.Append("            If a bill does not pass a fiscal committee by a specific date, it has stalled.If this occurs in the first year of the session,");
         sb.Append("            it becomes a two-year bill. In the first year, almost any bill becomes a two-year bill if it does not pass a specific deadline.However,");
         sb.Append("            a two-year bill that misses the house of origin deadline is dead for the two-year session, as called for in the California Constitution.");
         sb.Append("            Senate and Assembly procedural rules establishing these deadlines can be waived by the Rules Committee and/or the relevant house, and the");
         sb.Append("            previously stalled bill can regain life.");
         sb.Append("         </td>");
         sb.Append("      </tr>");
         sb.Append("   </table>");
         return sb.ToString();
      }
   }
}
